/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeWrapper */

#ifndef _Included_NativeWrapper
#define _Included_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeWrapper
 * Method:    performCalculation
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeWrapper_performCalculation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeWrapper
 * Method:    processString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeWrapper_processString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeWrapper
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeWrapper_initialize
  (JNIEnv *, jobject);

/*
 * Class:     NativeWrapper
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeWrapper_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
